### ISSUE TITLE
The extension doesn't work on firefox

### ISSUE THREAD

**Issue by thatDudo** [everyonesdesign/Chess-Helper#30]
I've installed the extension on the newest version of Firefox on Windows 10 and the extension is not able to make a move.
Every time I enter "a2a4" it says "Incorrect move: a2a4". The extension works on Chrome though.

**Comment by thatDudo** [comment]
I get it working sorry my bad you can delete this...

**Comment by everyonesdesign** [comment]
@thatDudo Hello! I'm glad you were able to figure out how to make it work. 
Could you share what was the issue?
