### ISSUE TITLE
the piece is moved and the pawn is promoted to queen on my screen but it is not shown on my friends game

### ISSUE THREAD

**Issue by zx950921** [everyonesdesign/Chess-Helper#34]
the current SAN input control  is not working with pawn promotion. i am playing with my friend, when I want to promote my pawn, I enter "bxa8=Q", the piece is moved and the pawn is promoted to queen on my screen but it is not shown on my friends game

**Comment by omercier01** [comment]
This may be related: promotion doesn't work on puzzles, e.g. this one [https://www.chess.com/puzzles/problem/1007830/practice](https://www.chess.com/puzzles/problem/1007830/practice)

**Comment by everyonesdesign** [comment]
It was tricky to reproduce the issue, but I found some rough edges for promotion moves.

Probably will be fixed in version 5.5

Feel free to reopen if the issue persists

**Comment by everyonesdesign** [comment]
I was able to reproduce the issue, it happens even in 5.5.1

Will research further

**Comment by everyonesdesign** [comment]
The solution was very simple (to mark keyboard moves with `userGenerated: true` field).

Will be shipped in 5.5.2

**Comment by zx950921** [comment]
thanks a lot really appreciate it
