### ISSUE TITLE
It does not work anymore?

### ISSUE THREAD

**Issue by tajo** [everyonesdesign/Chess-Helper#4]
Can anybody still run it?

**Comment by everyonesdesign** [comment]
@tajo Thank you very much for report. I can confirm that the extension doesn't work at the moment unfortunately. Probably chess.com changed markup of the website or did other changes.

I won't be able to focus on the fix maybe for 2 weeks or so. I'll try to take a look though, and if it's an easy fix, I'll try to apply it.

**Comment by everyonesdesign** [comment]
Added a hotfix, will release the updated version soon

**Comment by tajo** [comment]
Awesome! Thanks!

**Comment by everyonesdesign** [comment]
FYI, the fixed version is already published for Firefox.
The one for Chrome is "in review" by Google. Right after that it'll go live (they claim it can take up to 5 days, I guess it's some kind of formal procedure).

**Comment by KARM99** [comment]
@everyonesdesign is it already up? The current version seems not to work very well.

**Comment by sehe** [comment]
I'm wondering too. The extension almost works in Chrome - I can enter moves (and the arrows confirm it recognizing the move) but I can't "submit" the move (I'd assume pressing Enter should do the job, but it has no effect). Perhaps it is relevant that I'm in Puzzle mode.

**Comment by sehe** [comment]
Actually just tried in Firefox with the latest extension and it acts exactly the same as on Chrome. Maybe it is PEBCAK and I need to do something else than pressing Enter? @everyonesdesign

**Comment by everyonesdesign** [comment]
Hello, @sehe !

It should be submitted on Enter, so probably it's something with the extension. I'll check what I can do.

Could you provide following information:
- which page doesn't work for you (Live chess/Computer etc.)?
- also, do you participate in Chess.com beta program?

**Comment by everyonesdesign** [comment]
Also, could you check:
- extension version you use (the latest one is 5.0.0)
- potential extensions conflicts
- does it log errors in browser console, when move fails?

**Comment by everyonesdesign** [comment]
I'm closing the issue due to it being not active. Let me know if there're any cases still when the extension doesn't work
