### ISSUE TITLE
Extension has stopped working

### ISSUE THREAD

**Issue by epinu** [everyonesdesign/Chess-Helper#71]
Tried on both chrome and firefox. 

/blindfold works and invalid moves register as invalid but valid moves do not execute.

Absolutely love this extension - Hoping there is a simple fix.

**Comment by everyonesdesign** [comment]
Thank you for the report, I can reproduce the issue. I will look into fixing it.

**Comment by everyonesdesign** [comment]
The patch is added, this should be fixed when version 6.4.0 is approved by the extensions stores vendors (Google, Firefox, Opera, EDGE)
