### ISSUE TITLE
Question: Event Call on Game Result (Resign, Draw, Timeout, etc.)?

### ISSUE THREAD

**Issue by passee** [everyonesdesign/Chess-Helper#73]
Hi,

im using your code for a privat project and im trying to get an event, when a game is over, whenever its resigned, drawed, etc.

When I tried:
`this.game.onAll((ev: any) => {
	console.log("onall", ev.type);
});`
It doesnt trigger any event when the game is over. But when the game was already resigned it gave the event type "GameResigned".
Unfortunately, even after implementing in the TEventType and in the IGame interface it doesnt do anything.

Could you help me out here?

**Comment by everyonesdesign** [comment]
Hello @passee 

I haven't look into this project for a while, so not sure if there's some good way exposed by chess.com to catch this kind of events. I like your debugging approach, it makes sense; however it seems there's no relevant events emitted indeed.

As a rough workaround I want to suggest listening to all the events and checking if it's the first time when the game is over:

```
let gameOverCached = false;
this.game.onAll((ev) => {
  if (!gameOverCached && this.game.isGameOver()) {
    // here's the listener
   alert('Game ended!');
  }

 // reset to current in case if a new game is created later, to catch a new event in the future
 gameOverCached = this.game.isGameOver();
});
```

At the moment I cannot come up with something better than this. Note that the above approach also fires if you go to https://www.chess.com/play/online and start the first game (I guess it somehow marks the default blank one as over? not sure).

As a different approach, maybe you can explore other sources of events. Chessboard object seems to have all the data about game itself, moves etc, but maybe there's other objects on the page that expose better stage of the current user game (is it ongoing, is if finished) to render other things on the page. My extension mostly needs internal game data, so I'm not very knowledgeable of this part.

**Comment by passee** [comment]
Thanks for the fast reply!

I thought of the same workaround, unfortunately that doesnt work too, as no event gets triggered, after the game is over...

The other way would be a normal eventListerner to the class of the popup and watch if the display != none, which is what i was doing before, but thats not the best.

Im still a junior dev and I dont quiet understand how I could figure out other properties/methods on the objects. Could you explain to me how you where able to get all current existing ones in the interface?

**Comment by everyonesdesign** [comment]
Can you check again? It worked for me. For reproductability you can do following steps:

- go to https://www.chess.com/play/online
- start a new game
- run following snippet:

```
const interval = setInterval(() => { // interval is used just to wait until `wc-chess-board` element is created
  const cb = document.querySelector('wc-chess-board');
  if (cb) {
    clearInterval(interval);

    const game = cb.game;
    let gameOver = false;

    game.onAll(() => {
      if (!gameOver && game.getFinalPositionInfo().gameOver) {
        // here's the listener
        console.log('Game ended!');
      }

      // reset to false in case if a new game is created, to catch a new event in the future
      gameOver = game.getFinalPositionInfo().gameOver;
    });
  }
}, 50);
```

- play a game

> Im still a junior dev and I dont quiet understand how I could figure out other properties/methods on the objects. Could you explain to me how you where able to get all current existing ones in the interface?

TBH I don't have any universal solutions to tackle this, it's a bit of a creative area. I sometimes copy all the properties of window from a website I study (let's say chess.com) and some other website (e.g. Google, but it doesn't really matter), e.g. using a snippet like `copy([...Object.getOwnPropertyNames(window)].sort().join('\n'))` (run in Chrome console). Then you can make a diff out of these global properties to see what stands out. This makes it easier to look for some exposed APIs etc. You can do the same on a bigger scale looking for attributes by looping through DOM elements.

However, sometimes there's no good way to handle this exposed, then you have to come up with some workarounds. Very basic one for the case of monitoring end of game would be setting interval to check DOM elements (e.g. if one interval cycle there's "Resign" button and the next one there isn't you can assume that the game ended). It's quite an ugly solution, of course, but sometimes there's just not a lot to build upon.

**Comment by passee** [comment]
Thats insane mate!!
It works like a charm and I had no clue about Object.getOwnPropertyNames()

Thank you very much! :D

**Comment by everyonesdesign** [comment]
You're welcome! Glad I was able to help.
